name: Run Lint on Pull Request
# Callable Pylint

on:
  pull_request:
    branches:
      - main

jobs:
  lint_job:
    uses: splresearch/pocdart_documentation/.github/workflows/lint-reusable.yml@main
