name: Pylint

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Getting all changed Python files
      run: |
        changed_files=$(git diff --name-only  --diff-filter=ACMRTUXB origin/main | grep  -E "(.py$)") >> $GITHUB_ENV
    - name: Analysing changed code with pylint
      if: ${{ env.changed_files != '' }}
      run: |
        echo ${{ env.changed_files }}
        pylint --fail-under=9 ${{ env.changed_files }}
