name: Pylint Check
# Requires that changed files reach or exceed the 9.0 threshold

# Only run this Action when making a PR to main
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install requests
    - name: Analysing changed code with pylint
      run: |
        # For checking more file extensions, do something like "(.js$|.ts$|.tsx$)"
        changed_files=$(git diff --name-only  --diff-filter=ACMRTUXB origin/main | grep  -E "(.py$)")
        # For debug purposes
        #echo $changed_files
        pylint --fail-under=9 $changed_files
