name: Reusable Pylint Check

on:
  workflow_call:

# Step 1: Spin up a container with Python 3.7 to doing the checking in
# Step 2: Install dependencies needed
# Step 3: Gather changed files in PR and run them through pylint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint requests pytest mysql-connector-python

      - name: Analyse changed code with pylint
        run: |
          changed_files=$(git diff --name-only --diff-filter=ACMRTUXB origin/main | grep -E "(.py$)" || true)

          if [ -z "$changed_files" ]; then
            echo "No Python files changed. Skipping pylint."
            exit 0
          fi

          pylint --fail-under=8 $changed_files